# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('family_name', models.CharField(max_length=40)),
                ('birthday', models.DateField(blank=True)),
                ('course', models.CharField(max_length=10)),
                ('phone', models.CommaSeparatedIntegerField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('new', models.BooleanField()),
                ('confirmed', models.BooleanField()),
                ('dreamspark_key', models.BooleanField()),
                ('member_card', models.BooleanField()),
            ],
        ),
    ]
