# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='dreamspark_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
