# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_member_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
