# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_official',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('a', 'President'), ('b', 'Vice President'), ('c', 'Secretary'), ('e', 'Tech Leader'), ('g', 'Treasurer'), ('k', 'Media Manager'), ('z', 'Admin'), ('', 'Member')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
