# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20160303_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
