# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_decimal(apps, schema_editor):
    Member = apps.get_model('db', 'Member')
    rows = Member.objects.all()
    for row in rows:
        row.phone = row.phone.split(',')[0] or None
        row.save()


def migrate_course(apps, schema_editor):
    Member = apps.get_model('db', 'Member')
    Inscription = apps.get_model('db', 'Inscription')
    rows = Inscription.objects.all()
    for row in rows:
        if row.course:
            c = row.course
            c = c.upper()
            if c[:2] == 'LF':
                row.education = 'LF'
            elif c[:2] == 'LA':
                row.eduction = 'LA'
            if c[-1] == '1':
                row.year = '1'
            elif c[-1] == '2':
                row.year = '2'
            elif c[-1] == '3':
                row.year = '3'
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20160303_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='education',
            field=models.CharField(choices=[('LF', 'Licence Fondamentale'), ('LA', 'Licence Appliqué'), ('P', 'Préparatoire'), ('ENG', 'Ingéniorat'), ('MR', 'Master de Recherche'), ('MP', 'Master Professionnel'), ('PHD', 'Doctorat'), ('', 'Autre...')], default='LF', help_text='Cycle', max_length=3),
        ),
        migrations.AddField(
            model_name='inscription',
            name='inscription_num',
            field=models.DecimalField(decimal_places=0, help_text='Inscription Num', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='role',
            field=models.CharField(blank=True, choices=[('a', 'President'), ('b', 'Vice President'), ('c', 'Secretary'), ('e', 'Tech Leader'), ('g', 'Treasurer'), ('k', 'Media Manager'), ('z', 'Admin'), ('', 'Member')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='inscription',
            name='university',
            field=models.CharField(choices=[('FSS', 'Faculté des Sciences de Sfax'), ('ENIS', 'Ecole Nationale des Ingénieurs de Sfax'), ('ISIMS', "Institut Supérieur d'Informatique et de Multimédia de Sfax"), ('ENETCOM', "Ecole Nationale d'electronique et de télécommunications de Sfax"), ('FSEGS', 'Faculté des Sciences Economiques et de Gestion de Sfax'), ('IPEIS', "Institut Préparatoire aux Etudes d'Ingénieurs de Sfax"), ('', 'Autre...')], default='FSS', help_text='Institution / University', max_length=7),
        ),
        migrations.AddField(
            model_name='inscription',
            name='year',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default='1', help_text='Année', max_length=1),
        ),
        migrations.RunPython(migrate_decimal),
        migrations.RunPython(migrate_course),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, help_text='Addresse', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date de naissance / Birthday', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='E-mail', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_name',
            field=models.CharField(help_text='Nom / Family Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(help_text='Prénom / Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.DecimalField(decimal_places=0, help_text='Phone', max_digits=8),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, help_text='GitHub username', max_length=20),
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
