# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20160303_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
