# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20161014_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='inscription_num',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Inscription Num', max_digits=10, null=True),
        ),
    ]
