# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20161014_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='education',
            field=models.CharField(blank=True, choices=[('LF', 'Licence Fondamentale'), ('LA', 'Licence Appliqué'), ('P', 'Préparatoire'), ('ENG', 'Ingéniorat'), ('MR', 'Master de Recherche'), ('MP', 'Master Professionnel'), ('PHD', 'Doctorat'), ('', 'Autre...')], default='LF', max_length=3, verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='inscription_num',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Seulement pour les étudiants du FSS pour le service culturel de la faculté.', max_digits=10, null=True, verbose_name='Inscription Num'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='university',
            field=models.CharField(blank=True, choices=[('FSS', 'Faculté des Sciences de Sfax'), ('ENIS', 'Ecole Nationale des Ingénieurs de Sfax'), ('ISIMS', "Institut Supérieur d'Informatique et de Multimédia de Sfax"), ('ENETCOM', "Ecole Nationale d'electronique et de télécommunications de Sfax"), ('FSEGS', 'Faculté des Sciences Economiques et de Gestion de Sfax'), ('IPEIS', "Institut Préparatoire aux Etudes d'Ingénieurs de Sfax"), ('', 'Autre...')], default='FSS', max_length=7, verbose_name='Institution / University'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('', 'Autre')], default='1', max_length=1, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Addresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_name',
            field=models.CharField(max_length=40, verbose_name='Nom / Family Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Prénom / Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='GitHub username'),
        ),
    ]
