# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20161017_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('', 'Autre...')], default='1', max_length=1, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, help_text='Juste la Route (e.g: Rt Matar, Rt Sokra)', max_length=400, null=True, verbose_name='Addresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Phone'),
        ),
    ]
