# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20161023_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='university',
            field=models.CharField(blank=True, choices=[('FSS', 'Faculté des Sciences de Sfax'), ('ENIS', 'Ecole Nationale des Ingénieurs de Sfax'), ('ISIMS', "Institut Supérieur d'Informatique et de Multimédia de Sfax"), ('ENETCOM', "Ecole Nationale d'electronique et de télécommunications de Sfax"), ('FSEGS', 'Faculté des Sciences Economiques et de Gestion de Sfax'), ('IPEIS', "Institut Préparatoire aux Etudes d'Ingénieurs de Sfax"), ('ISGIS', 'Institut Supérieur de Gestion Industrielle de Sfax'), ('IPSAS', 'Institut Polytechnique Privé des Sciences Avancées de Sfax'), ('ISETS', 'Institut Supérieur des Etudes Technologiques de Sfax'), ('', 'Autre...')], default='FSS', max_length=7, verbose_name='Institution / University'),
        ),
    ]
