# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20161028_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='education',
            field=models.CharField(blank=True, choices=[('LF', 'Licence Fondamentale'), ('LA', 'Licence Appliqué'), ('P', 'Préparatoire'), ('ENG', 'Ingéniorat'), ('MR', 'Master de Recherche'), ('MP', 'Master Professionnel'), ('PHD', 'Doctorat'), ('', 'Autre...')], default='LF', max_length=3, verbose_name='Diplome courant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='session',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
