# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def migrate_date(apps, schema_editor):
    Inscription = apps.get_model('db', 'Inscription')
    rows = Inscription.objects.all()
    for row in rows:
        row.date = row.session
        row.save()


def migrate_session(apps, schema_editor):
    Inscription = apps.get_model('db', 'Inscription')
    rows = Inscription.objects.all()
    for row in rows:
        if row.date.month < 9:
            row.session = "%d-%d" % (row.date.year - 1, row.date.year)
        else:
            row.session = "%d-%d" % (row.date.year, row.date.year + 1)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20161029_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_date),
        migrations.AlterField(
            model_name='inscription',
            name='session',
            field=models.CharField(choices=[('2015-2016', '2015-2016'), ('2016-2017', '2016-2017')], default='2016-2017', max_length=9),
        ),
        migrations.RunPython(migrate_session),
    ]
