# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20161104_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
