# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20161108_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Price (-5 for members)'),
        ),
    ]
