# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20161111_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event End Time (UTC)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Event Start Time (UTC)'),
        ),
    ]
