# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:51
from __future__ import unicode_literals

from django.db import migrations


def migrate_from_db(apps, schema_editor):
    try:
        DbEvent = apps.get_model('db', 'Event')
        DbEventLink = apps.get_model('db', 'EventLink')
    except:
        # db app deleted ?!
        return
    Event = apps.get_model('event', 'Event')
    EventLink = apps.get_model('event', 'EventLink')
    Event.objects.bulk_create(
        Event(
            id=e.id,
            title=e.title,
            description=e.description,
            event_type=e.event_type,
            place=e.place,
            start=e.start,
            end=e.end,
            is_ours=e.is_ours,
            price=e.price)
        for e in DbEvent.objects.all())
    EventLink.objects.bulk_create(
        EventLink(
            id=e.id,
            title=e.title,
            link=e.link,
            event_id=e.event_id)
        for e in DbEventLink.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161112_2251'),
        ('db', '0026_auto_20161111_1349'),
    ]

    operations = [
        migrations.RunPython(migrate_from_db),
        migrations.RemoveField(
            model_name='eventlink',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventLink',
        ),
    ]
