# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20161112_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name', 'family_name')},
        ),
    ]
