# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20161113_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='inscription_num',
        ),
        migrations.AddField(
            model_name='member',
            name='cin',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
