# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20161120_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
