# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20161126_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='session',
            field=models.CharField(choices=[('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018')], default='2017-2018', max_length=9),
        ),
    ]
