# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
