# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20161104_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
