# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20161106_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
