# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20161107_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
