# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0021_auto_20161107_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set([('member', 'event')]),
        ),
    ]
