# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_register_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_type', models.CharField(blank=True, choices=[('con', 'conference'), ('cha', 'challenge'), ('tra', 'training'), ('tlk', 'talk')], max_length=3)),
                ('place', models.CharField(default='Faculty of Sciences of Sfax, Amphi A9', max_length=80)),
                ('start', models.DateTimeField(verbose_name='Event Start Time (UTC)')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Event End Time (UTC)')),
                ('is_ours', models.BooleanField()),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Price (-5 for members)')),
            ],
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('link', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
