# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 20:57
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
